### ISSUE TITLE
Missing underline on workbench selector

### ISSUE THREAD

**Issue by furgo16** [obelisk79/OpenTheme#96] opened 2024-07-05 22:02 UTC
The workbench selector, either in ComboBox or TabBar mode is missing the line below the widgets, which stands out from the rest of the toolbar buttons:

![image](https://github.com/obelisk79/OpenTheme/assets/148809153/ba0b2a35-82f8-4cd9-bf37-f1620736f013)

![image](https://github.com/obelisk79/OpenTheme/assets/148809153/a093ccf2-8af4-4809-964e-679a6d63e4e0)

```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38039 (Git) Snap 1067
Build type: Release
Branch: main
Hash: 7a9fd501c3ea0e259f843dc21f488ef6af43c201
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.7.3
  * Curves 0.6.40
  * ezydxf
  * Ondsel-Lens 2024.7.5.01
  * Assembly4 0.50.14
```

**Comment by obelisk79** [comment] 2024-07-05 22:24
This was an intentional style choice for the TabBar mode and isn't a bug. But when it is in the dropdown mode it should have the line. I'll see what I can do.

**Comment by maxwxyz** [comment] 2024-07-13 11:36
Duplicate of https://github.com/obelisk79/OpenTheme/issues/59

**Closed by maxwxyz** 2024-07-13 11:36 UTC
