### ISSUE TITLE
Measure annotation colors not set

### ISSUE THREAD

**Issue by adrianinsaval** [obelisk79/OpenTheme#31] opened 2024-05-03 06:39 UTC
I don't quite understand how my system got to having these colors configured by it was not my doing:
![image](https://github.com/obelisk79/OpenTheme/assets/36372335/34913b25-ae0f-4ad7-9742-eb60134bc8f3)
I don't think it's OpenTheme's fault either as it's probably not touching those at the moment, but I think both OpenDark and OpenLight should be configuring these colors too

**Comment by obelisk79** [comment] 2024-05-03 11:20
indeed, I'm working my way through the issues list from the bottom up. I'll push an update for this soon.

**Comment by maxwxyz** [comment] 2024-05-03 14:44
Duplicate of https://github.com/obelisk79/OpenTheme/issues/4

**Closed** 2024-05-03 17:48 UTC
